#!/bin/bash

echo "Running test"

export NODE_ENV=development
export PORT=3000
export DB_HOST=localhost
export DB_NAME=development
export DB_PORT=27017
export DB_SEED=false
export USERNAME=Mark
export PASSWORD=bullpup
export COOKIE_SECRET=abracadabra

./node_modules/.bin/mocha  --exit
